# Generated by Django 4.1.6 on 2023-09-12 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.CharField(max_length=100)),
                ("Lawyerid", models.IntegerField(max_length=100)),
                ("amount", models.IntegerField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("completed", models.BooleanField()),
                ("feedback", models.TextField(blank=True, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("paid", models.BooleanField()),
                ("query", models.TextField()),
                ("order_id", models.CharField(blank=True, max_length=100)),
                (
                    "transactionid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lawyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lawyertype", models.CharField(max_length=50)),
                ("phno", models.BigIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("Pincode", models.BigIntegerField()),
                ("enrollmentno", models.BigIntegerField()),
                ("enrollmentstate", models.CharField(max_length=100)),
                ("upi_id", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phno", models.BigIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("state", models.CharField(max_length=100)),
                ("Pincode", models.BigIntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
